export enum PATH {
    MAIN = '/',
    PROFILE = '/profile',
    LOGIN_FORM = '/login_form',
    LOGIN = 'login',
    REGISTRATION = 'registration',
    NEW_PASSWORD = 'new_pass',
    RECOVERY_PASSWORD = 'recovery',
    ERROR = '404',
    WRONG_PAGE = '*',
    TEST_PAGE = 'test',
    CARDS = '/cards',
    CARDS_TABLE = '/cards_table',
    LEARN = '/learn',
  }